image: "debian"

build:
    stage: build
    before_script:
        - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
        - apt update -qq
        - apt install -y -qq gcc-arm-none-eabi python3-pip git
        - apt install -y -qq -t stretch-backports meson
        - pip3 install crc16
    script:
        - ./bootstrap.sh
        - ninja -C build/
