# maintained by q3k, built using docker/build-env
image: "registry.k0.hswaw.net/q3k/card10-build-env:20190725-110707Z-4f3bf2a"

build:
    stage: build
    script:
        - ./bootstrap.sh
        - ninja -C build/
        - arm-none-eabi-size build/bootloader/bootloader.elf build/epicardium/epicardium.elf build/pycardium/pycardium.elf

pages:
    stage: deploy
    # maintaned by q3k, build using docker/deploy-env
    image: "registry.k0.hswaw.net/q3k/card10-deploy-env:20190725-112709Z-4c5d8e8"
    script:
        - export LD_LIBRARY_PATH=$(llvm-config --libdir)
        - echo $LD_LIBRARY_PATH
        - sphinx-build -b html Documentation/ Documentation/output/
        - mv Documentation/output/ public/
    artifacts:
        paths:
            - public/
    only:
        - master
