image: "debian"

build:
    stage: build
    before_script:
        - apt update -qq && apt install -y -qq gcc-arm-none-eabi python3-pip meson
        - pip3 install crc16
    script:
        - cd bootloader
        - make
        - cd ..
        - meson --cross-file card10-cross.ini build/
        - ninja -C build/
